import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.scss";
import { data } from "@/data/data";
import { useState } from "react";
import { Avatar, Badge, Button, Dialog, Text, TextInput } from "evergreen-ui";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const colours = [
    {
      light: "#ec676731",
      dark: "#B00000",
    },
    {
      light: "#a7fbee2f",
      dark: "#07a189",
    },
    {
      light: "#ffcd8234",
      dark: "#AC6700",
    },
    {
      light: "#34f93113",
      dark: "#068E04",
    },
    {
      light: "#cde6fdc0",
      dark: "#0B5396",
    },
    {
      light: "#d16dff25",
      dark: "#A636DB",
    },
    {
      light: "#a8a7f533",
      dark: "#2724C7",
    },
    {
      light: "#edebb171",
      dark: "#bdb95c",
    },
    {
      light: "#e0f8c170",
      dark: "#59A101",
    },
  ];

  const randomColour = () => {
    const random = Math.floor(Math.random() * colours.length);
    return colours[random];
  };
  const [isShown, setIsShown] = useState(false);
  const [isShownInfo, setIsShownInfo] = useState(false);

  const totalPages = Math.ceil(data.length / 10);
  const [currentPage, setCurrentPage] = useState(1);
  const [pageData, setPageData] = useState(data.slice(0, 10));

  const handlePageChange = (page) => {
    const start = (page - 1) * 10;
    const end = start + 10;
    setPageData(data.slice(start, end));
    setCurrentPage(page);
  };

  const handleNextPage = () => {
    if (currentPage < totalPages) {
      const start = currentPage * 10;
      const end = start + 10;
      setPageData(data.slice(start, end));
      setCurrentPage(currentPage + 1);
    }
  };

  const handlePrevPage = () => {
    if (currentPage > 1) {
      const start = (currentPage - 2) * 10;
      const end = start + 10;
      setPageData(data.slice(start, end));
      setCurrentPage(currentPage - 1);
    }
  };

  return (
    <>
      <Head>
        <title>Wooing Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <button>Logo</button>
        <div>
          <input
            type=""
            name=""
            defaultValue=""
            placeholder="What are you looking here eg. freelancer, projects"
          />
          <button>
            <svg
              width="22"
              height="21"
              viewBox="0 0 22 21"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M15.4852 13.5079L21.0257 19.0587C21.1928 19.2566 21.2791 19.5102 21.2673 19.7689C21.2555 20.0275 21.1465 20.2723 20.9621 20.4541C20.7777 20.6359 20.5315 20.7414 20.2727 20.7495C20.0138 20.7576 19.7615 20.6677 19.566 20.4978L14.0358 14.9676C12.3836 16.251 10.3044 16.8565 8.22147 16.6607C6.13854 16.465 4.20855 15.4827 2.82446 13.9138C1.44036 12.345 0.706251 10.3077 0.771594 8.21657C0.836937 6.12549 1.69682 4.13793 3.17616 2.65859C4.65551 1.17924 6.64307 0.319359 8.73415 0.254016C10.8252 0.188673 12.8626 0.922786 14.4314 2.30688C16.0002 3.69097 16.9826 5.62097 17.1783 7.70389C17.3741 9.78682 16.7686 11.866 15.4852 13.5182V13.5079ZM8.98868 14.6387C10.6244 14.6387 12.1932 13.9889 13.3498 12.8322C14.5064 11.6756 15.1562 10.1068 15.1562 8.4711C15.1562 6.83537 14.5064 5.26662 13.3498 4.10998C12.1932 2.95334 10.6244 2.30355 8.98868 2.30355C7.35294 2.30355 5.7842 2.95334 4.62756 4.10998C3.47092 5.26662 2.82112 6.83537 2.82112 8.4711C2.82112 10.1068 3.47092 11.6756 4.62756 12.8322C5.7842 13.9889 7.35294 14.6387 8.98868 14.6387V14.6387Z"
                fill="black"
              />
            </svg>
          </button>
        </div>
        <h5>Search Project</h5>
        <h5>Post Project</h5>
        <Image
          className={styles.logo}
          src="/images/message.svg"
          alt="message"
          width={180}
          height={37}
          priority
        />
        <Image
          className={styles.logo}
          src="/images/fav.svg"
          alt="fave"
          width={180}
          height={37}
          priority
        />
        <span> </span>
      </header>

      <main className={styles.main}>
        <section className={styles.top}>
          <Image
            className={styles.logo}
            src="/images/topbackground.svg"
            alt="fave"
            width={1080}
            height={1080}
            priority
          />
          <h1>Find Your Next Project</h1>
          <div>
            <input type="text" placeholder="Search your project" />
            <button>
              {" "}
              <svg
                width="22"
                height="21"
                viewBox="0 0 22 21"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  d="M15.4852 13.5079L21.0257 19.0587C21.1928 19.2566 21.2791 19.5102 21.2673 19.7689C21.2555 20.0275 21.1465 20.2723 20.9621 20.4541C20.7777 20.6359 20.5315 20.7414 20.2727 20.7495C20.0138 20.7576 19.7615 20.6677 19.566 20.4978L14.0358 14.9676C12.3836 16.251 10.3044 16.8565 8.22147 16.6607C6.13854 16.465 4.20855 15.4827 2.82446 13.9138C1.44036 12.345 0.706251 10.3077 0.771594 8.21657C0.836937 6.12549 1.69682 4.13793 3.17616 2.65859C4.65551 1.17924 6.64307 0.319359 8.73415 0.254016C10.8252 0.188673 12.8626 0.922786 14.4314 2.30688C16.0002 3.69097 16.9826 5.62097 17.1783 7.70389C17.3741 9.78682 16.7686 11.866 15.4852 13.5182V13.5079ZM8.98868 14.6387C10.6244 14.6387 12.1932 13.9889 13.3498 12.8322C14.5064 11.6756 15.1562 10.1068 15.1562 8.4711C15.1562 6.83537 14.5064 5.26662 13.3498 4.10998C12.1932 2.95334 10.6244 2.30355 8.98868 2.30355C7.35294 2.30355 5.7842 2.95334 4.62756 4.10998C3.47092 5.26662 2.82112 6.83537 2.82112 8.4711C2.82112 10.1068 3.47092 11.6756 4.62756 12.8322C5.7842 13.9889 7.35294 14.6387 8.98868 14.6387V14.6387Z"
                  fill="black"
                />
              </svg>
            </button>
          </div>
        </section>
        <section className={styles.middle}>
          <h4>
            <svg
              width="20"
              height="13"
              viewBox="0 0 20 13"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M7.77778 13H12.2222V10.8333H7.77778V13ZM0 0V2.16667H20V0H0ZM3.33333 7.58333H16.6667V5.41667H3.33333V7.58333Z"
                fill="#6C6C6C"
              />
            </svg>
            Filter By
          </h4>
          <div className={styles.filter}>
            <div>
              <label for="">Category</label>
              <select name="" id="">
                <option value="">All</option>
                <option value="">All</option>
                <option value="">All</option>
                <option value="">All</option>
                <option value="">All</option>
              </select>
            </div>
            <div>
              <label for="">Category</label>
              <select name="" id="">
                <option value="">All</option>
                <option value="">All</option>
                <option value="">All</option>
                <option value="">All</option>
                <option value="">All</option>
              </select>
            </div>
            <div>
              <label for="">Category</label>
              <select name="" id="">
                <option value="">All</option>
                <option value="">All</option>
                <option value="">All</option>
                <option value="">All</option>
                <option value="">All</option>
              </select>
            </div>
            <div>
              <label for="">Category</label>
              <select name="" id="">
                <option value="">All</option>
                <option value="">All</option>
                <option value="">All</option>
                <option value="">All</option>
                <option value="">All</option>
              </select>
            </div>
            <div>
              <label for="">Category</label>
              <select name="" id="">
                <option value="">All</option>
                <option value="">All</option>
                <option value="">All</option>
                <option value="">All</option>
                <option value="">All</option>
              </select>
            </div>
            <div>
              <label for="">Category</label>
              <select name="" id="">
                <option value="">All</option>
                <option value="">All</option>
                <option value="">All</option>
                <option value="">All</option>
                <option value="">All</option>
              </select>
            </div>
            <div>
              <span>Clear Filter</span>
            </div>
            <div>
              <button type="">Apply</button>
            </div>
          </div>
          <table>
            <thead>
              <tr>
                <th>Buyer</th>
                <th>Project Details</th>
                <th>Price</th>
                <th>Delivery Time</th>
                <th>Post Day</th>
                <th>Offer</th>
              </tr>
            </thead>
            <tbody>
              {pageData.map((item, index) => {
                const random1 = randomColour();
                const random2 = randomColour();
                return (
                  <tr key={index}>
                    <td onClick={() => setIsShownInfo(true)}>
                      {/* <Image
                        className={styles.logo}
                        src="/next.svg"
                        alt="Next.js Logo"
                        width={180}
                        height={37}
                        priority
                      /> */}
                      <div>
                        <svg
                          width="19"
                          height="21"
                          viewBox="0 0 19 21"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                          style={{
                            backgroundColor: random2.light,
                            color: random2.dark,
                          }}
                        >
                          <path
                            d="M9.13154 10.9584C8.04786 10.9584 6.98851 10.637 6.08746 10.035C5.18641 9.43292 4.48413 8.57719 4.06943 7.57599C3.65472 6.5748 3.54621 5.47312 3.75763 4.41026C3.96904 3.3474 4.49089 2.3711 5.25716 1.60482C6.02344 0.838542 6.99974 0.3167 8.0626 0.105284C9.12546 -0.106132 10.2271 0.00237406 11.2283 0.417081C12.2295 0.831789 13.0853 1.53407 13.6873 2.43512C14.2894 3.33617 14.6107 4.39551 14.6107 5.4792C14.6107 6.93237 14.0335 8.32602 13.0059 9.35357C11.9784 10.3811 10.5847 10.9584 9.13154 10.9584V10.9584ZM9.13154 1.8264C8.40909 1.8264 7.70286 2.04063 7.10216 2.44201C6.50146 2.84338 6.03327 3.41387 5.7568 4.08133C5.48032 4.74879 5.40799 5.48325 5.54893 6.19182C5.68988 6.9004 6.03777 7.55126 6.54862 8.06211C7.05948 8.57297 7.71034 8.92086 8.41892 9.06181C9.12749 9.20275 9.86194 9.13041 10.5294 8.85394C11.1969 8.57747 11.7674 8.10928 12.1687 7.50858C12.5701 6.90788 12.7843 6.20165 12.7843 5.4792C12.7843 4.51042 12.3995 3.58131 11.7145 2.89628C11.0294 2.21125 10.1003 1.8264 9.13154 1.8264Z"
                            fill="#B00000"
                          />
                          <path
                            d="M0 20.9992H1.8264V18.2596C1.8264 17.0486 2.30746 15.8872 3.16375 15.0309C4.02004 14.1746 5.18142 13.6936 6.39239 13.6936H11.8716C12.4712 13.6936 13.0649 13.8117 13.6189 14.0412C14.1729 14.2706 14.6762 14.6069 15.1002 15.0309C15.5242 15.4549 15.8606 15.9583 16.09 16.5122C16.3195 17.0662 16.4376 17.66 16.4376 18.2596V20.9992H18.264V18.2596C18.264 16.5642 17.5905 14.9383 16.3917 13.7395C15.1929 12.5407 13.567 11.8672 11.8716 11.8672H6.39239C4.69703 11.8672 3.0711 12.5407 1.87229 13.7395C0.673483 14.9383 0 16.5642 0 18.2596V20.9992Z"
                            fill="#B00000"
                          />
                        </svg>
                        {item.buyer}
                      </div>
                    </td>
                    <td>
                      <p>{item.projectDetails}</p>
                    </td>
                    <td>₹ {item.price}</td>
                    <td>
                      <span
                        style={{
                          backgroundColor: random2.light,
                          color: random2.dark,
                        }}
                      >
                        {item.deliveryTime}
                      </span>
                    </td>
                    <td>{item.postDay}</td>
                    <td>{item.offer}</td>
                    <td>
                      <button onClick={() => setIsShown(true)}>
                        <svg
                          width="23"
                          height="16"
                          viewBox="0 0 23 16"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            d="M14.5329 1.53193C14.6448 1.53205 14.7556 1.55394 14.8589 1.59635C14.9622 1.63876 15.056 1.70086 15.1349 1.77908L21.4457 7.92162L15.1426 14.2143C15.0637 14.295 14.9691 14.3592 14.8644 14.4031C14.7598 14.447 14.6472 14.4696 14.5334 14.4696C14.4194 14.4705 14.3062 14.4492 14.2006 14.4068C14.0949 14.3644 13.9988 14.3019 13.9178 14.2227C13.8368 14.1435 13.7725 14.0493 13.7286 13.9455C13.6847 13.8416 13.6622 13.7303 13.6622 13.6178V10.4794C13.6622 10.4794 12.5562 9.93457 10.6862 9.93457C8.50383 9.93457 5.28026 10.676 1.55423 13.8895C1.55423 13.8895 3.28386 5.36431 13.6622 5.36431V2.38624C13.6618 2.27361 13.6841 2.16203 13.7278 2.05796C13.7715 1.95389 13.8357 1.8594 13.9167 1.77994C13.9977 1.70049 14.0938 1.63766 14.1996 1.59509C14.3054 1.55252 14.4187 1.53105 14.5329 1.53193ZM14.5329 1.25344e-06C13.9153 -0.000621643 13.3206 0.230938 12.8701 0.647497C12.6278 0.869537 12.4349 1.1388 12.3038 1.4382C12.1726 1.73761 12.106 2.06062 12.1081 2.38675V3.89468C10.1154 4.05655 8.30025 4.53605 6.69702 5.32448C5.06782 6.12414 3.63574 7.26537 2.50115 8.66818C0.559137 11.0646 0.0520076 13.4871 0.0302513 13.5893C-0.0335179 13.9032 0.004089 14.2289 0.137788 14.5207C0.271488 14.8125 0.49456 15.0556 0.775662 15.216C1.05676 15.3763 1.38177 15.4458 1.70501 15.4147C2.02825 15.3836 2.33348 15.2535 2.57782 15.0425C6.00444 12.0864 8.87835 11.468 10.6862 11.468C11.1636 11.4665 11.64 11.5122 12.1081 11.6044V13.6178C12.1066 13.9435 12.1735 14.2659 12.3048 14.5647C12.436 14.8636 12.6287 15.1323 12.8706 15.354C13.3216 15.7697 13.9161 16.0007 14.5334 16C14.8529 16.0003 15.1692 15.9376 15.4637 15.8155C15.7581 15.6934 16.0248 15.5145 16.2481 15.2892L22.5517 8.99805C22.6951 8.85489 22.8085 8.68529 22.8854 8.49892C22.9623 8.31255 23.0013 8.11307 23 7.91187C22.9987 7.71067 22.9572 7.51169 22.8779 7.3263C22.7985 7.14091 22.683 6.97274 22.5377 6.83139L16.2263 0.68937C15.7767 0.247594 15.1677 -0.000328945 14.5329 1.25344e-06V1.25344e-06Z"
                            fill="white"
                          />
                        </svg>
                        Send Offer
                      </button>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
          <ul className={styles.mobile}>
            {pageData.map((item, index) => {
              const random1 = randomColour();
              const random2 = randomColour();
              return (
                <li key={index}>
                  <svg
                    onClick={() => setIsShownInfo(true)}
                    width="19"
                    height="21"
                    viewBox="0 0 19 21"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                    style={{
                      backgroundColor: random2.light,
                      color: random2.dark,
                    }}
                  >
                    <path
                      d="M9.13154 10.9584C8.04786 10.9584 6.98851 10.637 6.08746 10.035C5.18641 9.43292 4.48413 8.57719 4.06943 7.57599C3.65472 6.5748 3.54621 5.47312 3.75763 4.41026C3.96904 3.3474 4.49089 2.3711 5.25716 1.60482C6.02344 0.838542 6.99974 0.3167 8.0626 0.105284C9.12546 -0.106132 10.2271 0.00237406 11.2283 0.417081C12.2295 0.831789 13.0853 1.53407 13.6873 2.43512C14.2894 3.33617 14.6107 4.39551 14.6107 5.4792C14.6107 6.93237 14.0335 8.32602 13.0059 9.35357C11.9784 10.3811 10.5847 10.9584 9.13154 10.9584V10.9584ZM9.13154 1.8264C8.40909 1.8264 7.70286 2.04063 7.10216 2.44201C6.50146 2.84338 6.03327 3.41387 5.7568 4.08133C5.48032 4.74879 5.40799 5.48325 5.54893 6.19182C5.68988 6.9004 6.03777 7.55126 6.54862 8.06211C7.05948 8.57297 7.71034 8.92086 8.41892 9.06181C9.12749 9.20275 9.86194 9.13041 10.5294 8.85394C11.1969 8.57747 11.7674 8.10928 12.1687 7.50858C12.5701 6.90788 12.7843 6.20165 12.7843 5.4792C12.7843 4.51042 12.3995 3.58131 11.7145 2.89628C11.0294 2.21125 10.1003 1.8264 9.13154 1.8264Z"
                      fill="#B00000"
                    />
                    <path
                      d="M0 20.9992H1.8264V18.2596C1.8264 17.0486 2.30746 15.8872 3.16375 15.0309C4.02004 14.1746 5.18142 13.6936 6.39239 13.6936H11.8716C12.4712 13.6936 13.0649 13.8117 13.6189 14.0412C14.1729 14.2706 14.6762 14.6069 15.1002 15.0309C15.5242 15.4549 15.8606 15.9583 16.09 16.5122C16.3195 17.0662 16.4376 17.66 16.4376 18.2596V20.9992H18.264V18.2596C18.264 16.5642 17.5905 14.9383 16.3917 13.7395C15.1929 12.5407 13.567 11.8672 11.8716 11.8672H6.39239C4.69703 11.8672 3.0711 12.5407 1.87229 13.7395C0.673483 14.9383 0 16.5642 0 18.2596V20.9992Z"
                      fill="#B00000"
                    />
                  </svg>
                  <div>
                    <h3>{item.buyer}</h3>
                    <span>Price</span>
                    <span>Delvery Time</span>
                    <br />
                    <b>{item.price}/-</b>
                    <span
                      style={{
                        backgroundColor: random2.light,
                        color: random2.dark,
                      }}
                    >
                      {item.deliveryTime}
                    </span>
                  </div>
                  <div>
                    <p>{item.postDay}</p>
                    <button onClick={() => setIsShown(true)} type="">
                      <svg
                        width="23"
                        height="16"
                        viewBox="0 0 23 16"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          d="M14.5329 1.53193C14.6448 1.53205 14.7556 1.55394 14.8589 1.59635C14.9622 1.63876 15.056 1.70086 15.1349 1.77908L21.4457 7.92162L15.1426 14.2143C15.0637 14.295 14.9691 14.3592 14.8644 14.4031C14.7598 14.447 14.6472 14.4696 14.5334 14.4696C14.4194 14.4705 14.3062 14.4492 14.2006 14.4068C14.0949 14.3644 13.9988 14.3019 13.9178 14.2227C13.8368 14.1435 13.7725 14.0493 13.7286 13.9455C13.6847 13.8416 13.6622 13.7303 13.6622 13.6178V10.4794C13.6622 10.4794 12.5562 9.93457 10.6862 9.93457C8.50383 9.93457 5.28026 10.676 1.55423 13.8895C1.55423 13.8895 3.28386 5.36431 13.6622 5.36431V2.38624C13.6618 2.27361 13.6841 2.16203 13.7278 2.05796C13.7715 1.95389 13.8357 1.8594 13.9167 1.77994C13.9977 1.70049 14.0938 1.63766 14.1996 1.59509C14.3054 1.55252 14.4187 1.53105 14.5329 1.53193ZM14.5329 1.25344e-06C13.9153 -0.000621643 13.3206 0.230938 12.8701 0.647497C12.6278 0.869537 12.4349 1.1388 12.3038 1.4382C12.1726 1.73761 12.106 2.06062 12.1081 2.38675V3.89468C10.1154 4.05655 8.30025 4.53605 6.69702 5.32448C5.06782 6.12414 3.63574 7.26537 2.50115 8.66818C0.559137 11.0646 0.0520076 13.4871 0.0302513 13.5893C-0.0335179 13.9032 0.004089 14.2289 0.137788 14.5207C0.271488 14.8125 0.49456 15.0556 0.775662 15.216C1.05676 15.3763 1.38177 15.4458 1.70501 15.4147C2.02825 15.3836 2.33348 15.2535 2.57782 15.0425C6.00444 12.0864 8.87835 11.468 10.6862 11.468C11.1636 11.4665 11.64 11.5122 12.1081 11.6044V13.6178C12.1066 13.9435 12.1735 14.2659 12.3048 14.5647C12.436 14.8636 12.6287 15.1323 12.8706 15.354C13.3216 15.7697 13.9161 16.0007 14.5334 16C14.8529 16.0003 15.1692 15.9376 15.4637 15.8155C15.7581 15.6934 16.0248 15.5145 16.2481 15.2892L22.5517 8.99805C22.6951 8.85489 22.8085 8.68529 22.8854 8.49892C22.9623 8.31255 23.0013 8.11307 23 7.91187C22.9987 7.71067 22.9572 7.51169 22.8779 7.3263C22.7985 7.14091 22.683 6.97274 22.5377 6.83139L16.2263 0.68937C15.7767 0.247594 15.1677 -0.000328945 14.5329 1.25344e-06V1.25344e-06Z"
                          fill="white"
                        />
                      </svg>
                      Send Offer
                    </button>
                  </div>
                </li>
              );
            })}
          </ul>
          {/* pagination */}
          <div className={styles.pagination}>
            <button
              onClick={() => {
                handlePrevPage();
              }}
              className={styles.arrow}
            >
              {"<"}
            </button>
            {Array.from({ length: totalPages }, (_, i) => (
              <button
                onClick={() => {
                  handlePageChange(i + 1);
                }}
                className={currentPage === i + 1 ? styles.active : ""}
                key={i}
              >
                {i + 1}
              </button>
            ))}
            <button
              onClick={() => {
                handleNextPage();
              }}
              className={styles.arrow}
            >
              {">"}
            </button>
          </div>
        </section>
      </main>
      <footer className={styles.footer}>
        <ul>
          <li>
            <button>Logo</button>
          </li>
          <li>
            <address>1901 Thornridge Cir. Shiloh, Hawaii 81063</address>
          </li>
        </ul>
        <ul>
          <li>
            <b>Company</b>
          </li>
          <li>About Us</li>
          <li>Career</li>
          <li>Team</li>
          <li>Contact</li>
        </ul>
        <ul>
          <li>
            <b>Product</b>
          </li>
          <li>Service</li>
          <li>Freelancer</li>
          <li>Feature</li>
          <li>Development</li>
        </ul>
        <ul>
          <li>
            <b>Links</b>
          </li>
          <li>Privacy Policy</li>
          <li>Term & Conditions</li>
          <li>FAQ</li>{" "}
        </ul>
        <ul>
          <li>
            <b>Follow Us</b>
          </li>
          <li>
            <svg
              width="42"
              height="42"
              viewBox="0 0 42 42"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                fill-rule="evenodd"
                clip-rule="evenodd"
                d="M36.8686 0C39.7007 0 42 2.29934 42 5.13138V36.8686C42 39.7007 39.7007 42 36.8686 42H5.13138C2.29934 42 0 39.7007 0 36.8686V5.13138C0 2.29934 2.29925 0 5.13138 0H36.8686V0ZM16.0387 34.8259C27.1899 34.8259 33.2872 25.5856 33.2872 17.5773C33.2872 17.3134 33.2872 17.0493 33.2747 16.7979C34.4564 15.943 35.4873 14.8744 36.3045 13.6549C35.2233 14.1327 34.0541 14.4596 32.8221 14.6104C34.0793 13.8561 35.0347 12.6743 35.4873 11.2537C34.3182 11.9451 33.0232 12.4481 31.6404 12.7246C30.534 11.5429 28.9625 10.8137 27.2151 10.8137C23.8709 10.8137 21.1554 13.5293 21.1554 16.8733C21.1554 17.3511 21.2057 17.8162 21.3189 18.2562C16.2775 18.0048 11.8146 15.591 8.82246 11.92C8.30698 12.8126 8.00527 13.8561 8.00527 14.9624C8.00527 17.0619 9.07389 18.9226 10.7082 20.0037C9.71504 19.9785 8.78473 19.702 7.96753 19.2494V19.3248C7.96753 22.2666 10.0545 24.7056 12.8329 25.2713C12.33 25.4096 11.7894 25.4851 11.2362 25.4851C10.8465 25.4851 10.4694 25.4473 10.0922 25.3719C10.8591 27.7857 13.0969 29.5331 15.7495 29.5834C13.6752 31.2053 11.0603 32.1732 8.21904 32.1732C7.72874 32.1732 7.25099 32.1481 6.77324 32.0852C9.42588 33.8202 12.6191 34.8259 16.0387 34.8259Z"
                fill="black"
              />
            </svg>
            <svg
              width="42"
              height="42"
              viewBox="0 0 42 42"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                fill-rule="evenodd"
                clip-rule="evenodd"
                d="M36.8686 0C39.7007 0 42 2.29934 42 5.13138V36.8686C42 39.7007 39.7007 42 36.8686 42H28.1349V26.1749H33.5982L34.6377 19.3974H28.1349V14.9992C28.1349 13.145 29.0432 11.3376 31.9559 11.3376H34.9125V5.56754C34.9125 5.56754 32.2293 5.10964 29.664 5.10964C24.3083 5.10964 20.8079 8.35554 20.8079 14.2318V19.3974H14.8546V26.1749H20.8079V42H5.13138C2.29934 42 0 39.7007 0 36.8686V5.13138C0 2.29934 2.29925 0 5.13138 0H36.8686V0Z"
                fill="black"
              />
            </svg>
            <svg
              width="42"
              height="42"
              viewBox="0 0 42 42"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M20.9845 15.9414C19.9839 15.9414 19.0058 16.2381 18.1738 16.794C17.3418 17.35 16.6933 18.1401 16.3104 19.0646C15.9275 19.989 15.8273 21.0062 16.0225 21.9876C16.2177 22.969 16.6996 23.8705 17.4071 24.578C18.1147 25.2856 19.0161 25.7674 19.9975 25.9627C20.9789 26.1579 21.9962 26.0577 22.9206 25.6748C23.8451 25.2918 24.6352 24.6434 25.1911 23.8114C25.747 22.9794 26.0438 22.0013 26.0438 21.0006C26.0421 19.6594 25.5085 18.3735 24.5601 17.425C23.6117 16.4766 22.3258 15.9431 20.9845 15.9414Z"
                fill="black"
              />
              <path
                d="M26.9366 8.11328H15.0328C13.194 8.11541 11.4311 8.8468 10.1309 10.147C8.83069 11.4472 8.09929 13.2101 8.09717 15.0489V26.9527C8.09929 28.7915 8.83069 30.5544 10.1309 31.8546C11.4311 33.1548 13.194 33.8862 15.0328 33.8883H26.9366C28.7754 33.8862 30.5383 33.1548 31.8385 31.8546C33.1387 30.5544 33.8701 28.7915 33.8722 26.9527V15.0489C33.8701 13.2101 33.1387 11.4472 31.8385 10.147C30.5383 8.8468 28.7754 8.11541 26.9366 8.11328ZM20.9847 28.7328C19.4555 28.7328 17.9606 28.2793 16.689 27.4297C15.4175 26.5801 14.4265 25.3725 13.8413 23.9597C13.2561 22.5469 13.1029 20.9922 13.4013 19.4924C13.6996 17.9925 14.436 16.6148 15.5174 15.5335C16.5987 14.4521 17.9764 13.7157 19.4763 13.4174C20.9761 13.1191 22.5308 13.2722 23.9436 13.8574C25.3564 14.4426 26.564 15.4336 27.4136 16.7051C28.2632 17.9767 28.7167 19.4716 28.7167 21.0008C28.7143 23.0507 27.8989 25.016 26.4494 26.4655C24.9999 27.915 23.0346 28.7304 20.9847 28.7328ZM29.4809 14.4407C29.1034 14.4407 28.7344 14.3287 28.4204 14.1191C28.1065 13.9094 27.8618 13.6113 27.7172 13.2626C27.5726 12.9139 27.5346 12.5301 27.6081 12.1598C27.6815 11.7895 27.8631 11.4493 28.1299 11.1821C28.3966 10.915 28.7366 10.7329 29.1068 10.659C29.477 10.585 29.8608 10.6224 30.2098 10.7665C30.5587 10.9106 30.8571 11.1549 31.0672 11.4686C31.2774 11.7822 31.3898 12.1511 31.3903 12.5286C31.3908 12.7797 31.3417 13.0283 31.246 13.2604C31.1503 13.4925 31.0097 13.7034 30.8323 13.8811C30.655 14.0587 30.4443 14.1997 30.2125 14.2959C29.9806 14.392 29.732 14.4416 29.4809 14.4416V14.4407Z"
                fill="black"
              />
              <path
                d="M41.9284 9.82684C41.9259 9.07042 41.8566 8.3157 41.7215 7.57145C41.5485 6.6627 41.305 5.77714 40.8698 4.95578C40.4165 4.09041 39.8266 3.30383 39.1227 2.62638C38.0596 1.58562 36.7463 0.836211 35.3094 0.450363C33.9868 0.0936399 32.6339 0.0187279 31.2775 0.0205116C31.273 0.0145339 31.2702 0.00744103 31.2695 0H10.6919C10.6919 0.00713447 10.6919 0.0142689 10.6919 0.0205116C9.92048 0.0347805 9.14728 0.0285378 8.38032 0.123961C7.53927 0.212883 6.71127 0.398413 5.91269 0.676883C4.6707 1.13501 3.54973 1.87073 2.63529 2.82792C1.58708 3.89317 0.832237 5.21146 0.444121 6.65467C0.0927481 7.96742 0.0160525 9.30602 0.0142689 10.6544L0 31.315C0.0249706 32.2469 0.0329969 33.1878 0.189955 34.1117C0.356723 35.0927 0.594836 36.0478 1.04966 36.9378C1.65458 38.1304 2.51657 39.1739 3.57348 39.9931C4.32792 40.5945 5.18261 41.0579 6.09819 41.3621C7.4466 41.7973 8.83782 41.964 10.2496 41.9721C11.1307 41.9774 12.01 41.9997 12.8911 41.9962C19.2889 41.9694 25.6877 42.0425 32.0855 41.9569C32.9307 41.9384 33.7728 41.8489 34.6031 41.6894C36.1731 41.4128 37.6342 40.7015 38.8204 39.6364C40.2277 38.3808 41.1775 36.8451 41.6064 34.991C41.8873 33.779 41.9569 32.5492 41.9694 31.3159V31.0697C41.9685 30.9734 41.9319 10.1033 41.9284 9.82684ZM36.5436 26.9496C36.5406 29.4968 35.5274 31.9388 33.7263 33.74C31.9253 35.5412 29.4834 36.5546 26.9362 36.5579H15.0323C12.485 36.5548 10.0428 35.5415 8.24159 33.7403C6.44034 31.939 5.42705 29.4969 5.42398 26.9496V15.0457C5.42705 12.4984 6.44034 10.0562 8.24159 8.25496C10.0428 6.45371 12.485 5.44042 15.0323 5.43736H26.9362C29.4835 5.44042 31.9257 6.45371 33.7269 8.25496C35.5282 10.0562 36.5415 12.4984 36.5445 15.0457L36.5436 26.9496Z"
                fill="black"
              />
            </svg>
          </li>
        </ul>
      </footer>

      <Dialog
        isShown={isShown}
        title="Send Offer"
        onCloseComplete={() => setIsShown(false)}
        hasFooter={false}
        backgroundColor="#07a189"
        style={{ backgroundColor: "#07a189" }}
      >
        <hr />
        <div
          style={{
            width: "100%",
            margin: "20px 0",
            display: "flex",
            flexDirection: "column",
          }}
        >
          <label
            for=""
            style={{
              color: "#1d201f",
              fontSize: "14px",
              marginBottom: "5px",
            }}
          >
            Total Offer Amount
          </label>
          <TextInput
            name="text-input-name"
            placeholder="Text input placeholder..."
            style={{
              border: "1px solid #07a189",
              width: "100%",
            }}
          />
        </div>
        <div
          style={{
            width: "100%",
            margin: "20px 0",
            display: "flex",
            flexDirection: "column",
          }}
        >
          <label
            style={{
              color: "#1d201f",
              fontSize: "14px",
              marginBottom: "5px",
            }}
            for=""
          >
            Delivery Time
          </label>
          <TextInput
            name="text-input-name"
            placeholder="Text input placeholder..."
            style={{
              width: "100%",

              border: "1px solid #07a189",
            }}
          />
        </div>
        <div
          style={{
            width: "100%",
            margin: "20px 0",
            display: "flex",
            flexDirection: "column",
          }}
        >
          <label
            style={{
              color: "#1d201f",
              fontSize: "14px",
              marginBottom: "5px",
            }}
            for=""
          >
            Description
          </label>
          <TextInput
            name="text-input-name"
            placeholder="Text input placeholder..."
            style={{
              width: "100%",

              border: "1px solid #07a189",
            }}
          />
        </div>
        <Button
          marginRight={16}
          style={{
            width: "100%",
            background: "#1d201f",
            color: "white",
            border: "1px solid #07a189",
          }}
          onClick={() => setIsShown(false)}
        >
          Send
        </Button>
      </Dialog>
      <Dialog
        isShown={isShownInfo}
        title="Search Project Details"
        onCloseComplete={() => setIsShownInfo(false)}
        hasFooter={false}
        backgroundColor="#07a189"
        style={{ backgroundColor: "#07a189" }}
      >
        <hr />
        <div
          style={{
            width: "100%",
            margin: "20px 0",
            display: "flex",
            color: "#1d201f",
            alignItems: "start",
          }}
        >
          <div
            style={{
              width: "60%",
              display: "flex",
              flexDirection: "column",
            }}
          >
            <h6 style={{ marginBottom: "10px" }}>Buyer</h6>
            <div
              style={{
                width: "60%",
                display: "flex",
                alignItems: "center",
              }}
            >
              <Avatar name="Steve Jobs" size={40} marginRight={16} />

              <Text>Albert Flores</Text>
            </div>
          </div>
          <div>
            <h6 style={{ marginBottom: "10px" }}>Delivery Time</h6>
            <div>
              <Badge color="green">Success</Badge>
            </div>
          </div>
        </div>

        <div
          style={{
            width: "100%",
            margin: "20px 0",
            display: "flex",
            color: "#1d201f",

            flexDirection: "column",
          }}
        >
          <h6 style={{ marginBottom: "10px" }}>Delivery Time</h6>
          <div>
            <Text>
              <b>8000 /-</b>
            </Text>
          </div>
        </div>
        <ul
          style={{
            width: "100%",
            margin: "20px 0",
            display: "flex",
            flexDirection: "column",
            color: "#1d201f",
            fontSize: "14px",
          }}
        >
          <h6
            style={{
              fontSize: "16px",

              marginBottom: "10px",
            }}
          >
            Description
          </h6>
          <li>
            Lorem ipsum doloripsum doloripsum doloripsum dolor sit amet,
            consectetur adipiscing elit.
          </li>
          <li>
            Lorem ipsum dolor sit amet, consectetur adipiscingipsum dolor elit.
          </li>
          <li>
            Lorem ipsum dolor sit amet, consectetur adipipsum doloriscing elit.
          </li>
          <li>
            Lorem ipsum dolor sit amet, consectetur adipiscingipsum doloripsum
            dolor elit.
          </li>
          <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
          <li>
            Lorem ipsum dolor sit amet, consectetur adipiscing eipsum doloripsum
            doloripsum dolorlit.
          </li>
        </ul>
        <div
          style={{
            width: "100%",
            margin: "20px 0",
            display: "flex",
            color: "#1d201f",
            alignItems: "start",
          }}
        >
          <div
            style={{
              width: "60%",
              display: "flex",
              flexDirection: "column",
            }}
          >
            <h6 style={{ marginBottom: "10px" }}>Buyer</h6>
            <div
              style={{
                width: "60%",
                display: "flex",
                alignItems: "center",
              }}
            >
              <Text>
                <b>06 Days Ago</b>
              </Text>
            </div>
          </div>
          <div>
            <h6 style={{ marginBottom: "10px" }}>Delivery Time</h6>
            <div>
              <Text>
                <b>25</b>
              </Text>
            </div>
          </div>
        </div>

        <h6
          style={{
            marginBottom: "10px",
            color: "#c5c5c5",
            fontSize: "15px",
            fontWeight: "400",
          }}
        >
          Offer Update
        </h6>

        <Button
          marginRight={16}
          style={{
            width: "35%",
            background: "#1d201f",
            color: "white",
            // border: "1px solid #07a189",
          }}
          onClick={() => setIsShownInfo(false)}
        >
          <svg
            width="23"
            height="16"
            viewBox="0 0 23 16"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
            style={{
              width: "20px",
              height: "20px",
              marginRight: "5px",
              background: "#1d201f",
              // color: "white",
            }}
          >
            <path
              d="M14.5329 1.53193C14.6448 1.53205 14.7556 1.55394 14.8589 1.59635C14.9622 1.63876 15.056 1.70086 15.1349 1.77908L21.4457 7.92162L15.1426 14.2143C15.0637 14.295 14.9691 14.3592 14.8644 14.4031C14.7598 14.447 14.6472 14.4696 14.5334 14.4696C14.4194 14.4705 14.3062 14.4492 14.2006 14.4068C14.0949 14.3644 13.9988 14.3019 13.9178 14.2227C13.8368 14.1435 13.7725 14.0493 13.7286 13.9455C13.6847 13.8416 13.6622 13.7303 13.6622 13.6178V10.4794C13.6622 10.4794 12.5562 9.93457 10.6862 9.93457C8.50383 9.93457 5.28026 10.676 1.55423 13.8895C1.55423 13.8895 3.28386 5.36431 13.6622 5.36431V2.38624C13.6618 2.27361 13.6841 2.16203 13.7278 2.05796C13.7715 1.95389 13.8357 1.8594 13.9167 1.77994C13.9977 1.70049 14.0938 1.63766 14.1996 1.59509C14.3054 1.55252 14.4187 1.53105 14.5329 1.53193ZM14.5329 1.25344e-06C13.9153 -0.000621643 13.3206 0.230938 12.8701 0.647497C12.6278 0.869537 12.4349 1.1388 12.3038 1.4382C12.1726 1.73761 12.106 2.06062 12.1081 2.38675V3.89468C10.1154 4.05655 8.30025 4.53605 6.69702 5.32448C5.06782 6.12414 3.63574 7.26537 2.50115 8.66818C0.559137 11.0646 0.0520076 13.4871 0.0302513 13.5893C-0.0335179 13.9032 0.004089 14.2289 0.137788 14.5207C0.271488 14.8125 0.49456 15.0556 0.775662 15.216C1.05676 15.3763 1.38177 15.4458 1.70501 15.4147C2.02825 15.3836 2.33348 15.2535 2.57782 15.0425C6.00444 12.0864 8.87835 11.468 10.6862 11.468C11.1636 11.4665 11.64 11.5122 12.1081 11.6044V13.6178C12.1066 13.9435 12.1735 14.2659 12.3048 14.5647C12.436 14.8636 12.6287 15.1323 12.8706 15.354C13.3216 15.7697 13.9161 16.0007 14.5334 16C14.8529 16.0003 15.1692 15.9376 15.4637 15.8155C15.7581 15.6934 16.0248 15.5145 16.2481 15.2892L22.5517 8.99805C22.6951 8.85489 22.8085 8.68529 22.8854 8.49892C22.9623 8.31255 23.0013 8.11307 23 7.91187C22.9987 7.71067 22.9572 7.51169 22.8779 7.3263C22.7985 7.14091 22.683 6.97274 22.5377 6.83139L16.2263 0.68937C15.7767 0.247594 15.1677 -0.000328945 14.5329 1.25344e-06V1.25344e-06Z"
              fill="white"
            />
          </svg>
          Send Offer
        </Button>
      </Dialog>
    </>
  );
}
